name: Deployment

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deployment:
    strategy:
      matrix:
        host: [switch-worker-1, switch-worker-2, switch-worker-3]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Login via ssh + run update script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: /usr/bin/env bash /home/wchill/${{ github.event.repository.name }}/update.sh
          host: ${{ matrix.host }}
          username: wchill
          privateKey: ${{ secrets.PRIVATE_KEY }}
